media:
  input: src/images
  output: ""
content:
  - name: projects
    label: Projects
    path: src/content/student_projects
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: type
        label: Type
        type: string
      - name: visible
        label: Visible
        type: boolean
        default: true
      - name: image
        label: Image
        type: image
      - name: body
        label: Description
        type: rich-text
  - name: news
    label: News
    path: src/content/news.yaml
    type: file
    format: raw