media:
  input: src/images
  output: /
content:
  - name: projects
    label: Projects
    path: src/content/student_projects
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
    fields:
      - name: title
        label: Title
        type: text
      - name: type
        label: Type
        type: string