name: Publish Docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '0 2 * * *'
jobs:
  push_to_registry:
    name: Push Docker image to Registry
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitLab Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.uni-bonn.de
          username: ${{ secrets.BONN_GITLAB_USERNAME }}
          password: ${{ secrets.BONN_GITLAB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          provenance: false
          tags: registry.gitlab.uni-bonn.de/rpl/containers/website:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
